const mongoose = require('mongoose');

const jobSchema = new mongoose.Schema({
  // Unique job identifier (automatically generated by MongoDB)
  title: { 
    type: String, 
    required: true,
    description: "Job title"
  },
  description: { 
    type: String, 
    required: true,
    description: "Job description"
  },
  company: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'Company', 
    required: true,
    description: "References Employer (Company._id)"
  },
  requirements: { 
    type: String, 
    required: true,
    description: "Required skills"
  },
  location: { 
    type: String, 
    required: true,
    description: "Job location"
  },
  minsalary: { 
    type: Number,
    description: "Min Salary Offered"
  },
  maxsalary:{
    type:Number,
    description:"Max Salary Offered"
  }
  
},{timestamps:true});

module.exports = mongoose.model('Job', jobSchema);
